/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab7p2_victorvalladares_12141026;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author valla
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_equipo = new javax.swing.JMenu();
        crear = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        cargar_ar = new javax.swing.JMenuItem();
        menu_partidos = new javax.swing.JMenu();
        simular = new javax.swing.JMenuItem();
        tabla_pos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_equipo.setText("Equipos");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        menu_equipo.add(crear);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        menu_equipo.add(modificar);

        eliminar.setText("Eliminar");
        menu_equipo.add(eliminar);

        cargar_ar.setText("Cargar Archivo");
        menu_equipo.add(cargar_ar);

        jMenuBar1.add(menu_equipo);

        menu_partidos.setText("Partidos y tabla");

        simular.setText("Simulacion");
        menu_partidos.add(simular);

        tabla_pos.setText("Tabla de posiciones");
        tabla_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabla_posActionPerformed(evt);
            }
        });
        menu_partidos.add(tabla_pos);

        jMenuBar1.add(menu_partidos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void tabla_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabla_posActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_posActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try{
            archivo =new File("./equipos.txt");
            fw = new FileWriter (archivo);
            bw = new BufferedWriter (fw);
            
            String nombre, nota;
            nombre = JOptionPane.showInputDialog("nombre");
            Equipos x = new Equipos(nombre,0,0,0,0,0,0,0,0);
            lista.add(x);
            
            bw.write(nombre + "," + x.getPartidos() +"," + x.getGanados() + "," + x.getEmpatados() + "," + x.getPerdidios() + "," +
            x.getGf()+","+x.getGc()+","+x.getDiff()+","+x.getPts());
            
            bw.newLine();
            bw.flush();
            
            bw.close();
            fw.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrio un error al agregar");
        }  
    }//GEN-LAST:event_crearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cargar_ar;
    private javax.swing.JMenuItem crear;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_equipo;
    private javax.swing.JMenu menu_partidos;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JMenuItem simular;
    private javax.swing.JMenuItem tabla_pos;
    // End of variables declaration//GEN-END:variables
    
    ArrayList <Equipos> lista = new ArrayList ();
}
