/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab7p2_victorvalladares_12141026;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author valla
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_modificar = new javax.swing.JDialog();
        cb_modificar = new javax.swing.JComboBox<>();
        bt_modificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_nuevo_nombre = new javax.swing.JTextField();
        jd_eliminar = new javax.swing.JDialog();
        cb_eliminar = new javax.swing.JComboBox<>();
        bt_eliminar = new javax.swing.JButton();
        jd_tabla = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jd_simulacion = new javax.swing.JDialog();
        cb_equipo1 = new javax.swing.JComboBox<>();
        cb_equipo2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        marcador_local = new javax.swing.JLabel();
        marcador_visitante = new javax.swing.JLabel();
        bt_simular = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_equipo = new javax.swing.JMenu();
        crear = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        cargar_ar = new javax.swing.JMenuItem();
        menu_partidos = new javax.swing.JMenu();
        simular = new javax.swing.JMenuItem();
        tabla_pos = new javax.swing.JMenuItem();

        bt_modificar.setText("Modificar");
        bt_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarMouseClicked(evt);
            }
        });

        jLabel4.setText("Nuevo Nombre");

        javax.swing.GroupLayout jd_modificarLayout = new javax.swing.GroupLayout(jd_modificar.getContentPane());
        jd_modificar.getContentPane().setLayout(jd_modificarLayout);
        jd_modificarLayout.setHorizontalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addComponent(bt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modificarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nuevo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jd_modificarLayout.setVerticalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nuevo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(bt_modificar)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminarLayout = new javax.swing.GroupLayout(jd_eliminar.getContentPane());
        jd_eliminar.getContentPane().setLayout(jd_eliminarLayout);
        jd_eliminarLayout.setHorizontalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGroup(jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jd_eliminarLayout.setVerticalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jd_tablaLayout = new javax.swing.GroupLayout(jd_tabla.getContentPane());
        jd_tabla.getContentPane().setLayout(jd_tablaLayout);
        jd_tablaLayout.setHorizontalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_tablaLayout.setVerticalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jLabel1.setText("LOCAL");

        jLabel2.setText("VISITANTE");

        jLabel3.setText("VS");

        marcador_local.setText("0");

        marcador_visitante.setText("0");

        bt_simular.setText("SIMULAR");
        bt_simular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_simularMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_simulacionLayout = new javax.swing.GroupLayout(jd_simulacion.getContentPane());
        jd_simulacion.getContentPane().setLayout(jd_simulacionLayout);
        jd_simulacionLayout.setHorizontalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(marcador_local)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addComponent(cb_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addComponent(cb_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marcador_visitante)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(bt_simular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_simulacionLayout.setVerticalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(marcador_local)
                    .addComponent(marcador_visitante))
                .addGap(34, 34, 34)
                .addComponent(bt_simular)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_equipo.setText("Equipos");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        menu_equipo.add(crear);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        menu_equipo.add(modificar);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        menu_equipo.add(eliminar);

        cargar_ar.setText("Cargar Archivo");
        cargar_ar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_arActionPerformed(evt);
            }
        });
        menu_equipo.add(cargar_ar);

        jMenuBar1.add(menu_equipo);

        menu_partidos.setText("Partidos y tabla");

        simular.setText("Simulacion");
        simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularActionPerformed(evt);
            }
        });
        menu_partidos.add(simular);

        tabla_pos.setText("Tabla de posiciones");
        tabla_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabla_posActionPerformed(evt);
            }
        });
        menu_partidos.add(tabla_pos);

        jMenuBar1.add(menu_partidos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        jd_modificar.pack();
        jd_modificar.setLocationRelativeTo(this);
        jd_modificar.setVisible(true);
    }//GEN-LAST:event_modificarActionPerformed

    private void tabla_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabla_posActionPerformed
        ordenar();
        tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "PJ", "G", "E", "P", "GF", "GC", "DG", "Pts"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        
        for (Equipos equipo : lista){
            Object[] newrow = {
                equipo.getNombre(),
                equipo.getPartidos(),
                equipo.getGanados(),
                equipo.getEmpatados(),
                equipo.getPerdidios(),
                equipo.getGf(),
                equipo.getGc(),
                equipo.getDiff(),
                equipo.getPts()
            };  
            DefaultTableModel modelo
                        = (DefaultTableModel) tabla.getModel();
            modelo.addRow(newrow);
            tabla.setModel(modelo);
        }
        
        jd_tabla.pack();
        jd_tabla.setLocationRelativeTo(this);
        jd_tabla.setVisible(true);
    }//GEN-LAST:event_tabla_posActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        try{
            
            String nombre;
            nombre = JOptionPane.showInputDialog("nombre");
            Equipos x = new Equipos(nombre,0,0,0,0,0,0,0,0);
            
            lista.add(x);
            
            DefaultComboBoxModel dc=
                    (DefaultComboBoxModel) cb_equipo1.getModel();
            dc.addElement(x);
            
            cb_equipo1.setModel(dc);
            cb_modificar.setModel(dc);
            cb_eliminar.setModel(dc);
            
            
            DefaultComboBoxModel cb=
                    (DefaultComboBoxModel) cb_equipo2.getModel();
            cb.addElement(x);
            cb_equipo2.setModel(cb);
            
            
            AdministrarEquipos ae=
                new AdministrarEquipos("./equipos.txt");        
            ae.cargarArchivo();
            
            ae.getListaEquipos().add(x);
            ae.escribirArchivo();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrio un error al agregar");
        }  
    }//GEN-LAST:event_crearActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        jd_eliminar.pack();
        jd_eliminar.setLocationRelativeTo(this);
        jd_eliminar.setVisible(true);
    }//GEN-LAST:event_eliminarActionPerformed

    private void simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularActionPerformed
        jd_simulacion.pack();
        jd_simulacion.setLocationRelativeTo(this);
        jd_simulacion.setVisible(true);
    }//GEN-LAST:event_simularActionPerformed

    private void bt_simularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_simularMouseClicked
        partido();
    }//GEN-LAST:event_bt_simularMouseClicked

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        try{  
            lista.remove(cb_eliminar.getSelectedIndex());
            int pos = cb_modificar.getSelectedIndex();
            
            AdministrarEquipos ae=
                new AdministrarEquipos("./equipos.txt");  

            ae.cargarArchivo();
            ae.getListaEquipos().remove(pos); 
            ae.escribirArchivo();
            
            DefaultComboBoxModel dc=
                    (DefaultComboBoxModel) cb_eliminar.getModel();
            cb_eliminar.remove(cb_eliminar.getSelectedIndex());
            cb_equipo1.setModel(dc);
            cb_modificar.setModel(dc);
            cb_eliminar.setModel(dc);


            DefaultComboBoxModel cb=
                    (DefaultComboBoxModel) cb_eliminar.getModel();
            cb_eliminar.remove(cb_eliminar.getSelectedIndex());
            cb_equipo2.setModel(cb);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se ha podido eliminar ya que no hay autos que eliminar");
        }
  
        
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void bt_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarMouseClicked
        try {
            Equipos modificar = (Equipos) cb_modificar.getSelectedItem();
            int pos = cb_modificar.getSelectedIndex();
            modificar.setNombre(tf_nuevo_nombre.getText());

            AdministrarEquipos ae=
                new AdministrarEquipos("./equipos.txt");  

            ae.cargarArchivo();
            ae.getListaEquipos().get(pos).setNombre(tf_nuevo_nombre.getText()); 
            ae.escribirArchivo();


            DefaultComboBoxModel dc=
                    (DefaultComboBoxModel) cb_modificar.getModel();
            
            cb_equipo1.setModel(dc);
            cb_modificar.setModel(dc);
            cb_eliminar.setModel(dc);


            DefaultComboBoxModel cb=
                    (DefaultComboBoxModel) cb_modificar.getModel();
            cb_equipo2.setModel(cb);

            tf_nuevo_nombre.setText("");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
        
    }//GEN-LAST:event_bt_modificarMouseClicked

    private void cargar_arActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_arActionPerformed
        try{
           AdministrarEquipos ae=
                    new AdministrarEquipos("./equipos.txt");        
            ae.cargarArchivo();
            for (Equipos t : ae.getListaEquipos()) {
                DefaultComboBoxModel dc=
                    (DefaultComboBoxModel) cb_equipo1.getModel();
                dc.addElement(t);
            
                cb_equipo1.setModel(dc);
                cb_modificar.setModel(dc);
                cb_eliminar.setModel(dc);
            
            
                DefaultComboBoxModel cb=
                        (DefaultComboBoxModel) cb_equipo2.getModel();
                cb.addElement(t);
                cb_equipo2.setModel(cb);
                lista.add(t);
            } 
        }catch(Exception e){
            
        }    
        
    }//GEN-LAST:event_cargar_arActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_simular;
    private javax.swing.JMenuItem cargar_ar;
    private javax.swing.JComboBox<String> cb_eliminar;
    private javax.swing.JComboBox<String> cb_equipo1;
    private javax.swing.JComboBox<String> cb_equipo2;
    private javax.swing.JComboBox<String> cb_modificar;
    private javax.swing.JMenuItem crear;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_eliminar;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JDialog jd_simulacion;
    private javax.swing.JDialog jd_tabla;
    private javax.swing.JLabel marcador_local;
    private javax.swing.JLabel marcador_visitante;
    private javax.swing.JMenu menu_equipo;
    private javax.swing.JMenu menu_partidos;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JMenuItem simular;
    private javax.swing.JTable tabla;
    private javax.swing.JMenuItem tabla_pos;
    private javax.swing.JTextField tf_nuevo_nombre;
    // End of variables declaration//GEN-END:variables
    
    ArrayList <Equipos> lista = new ArrayList ();
    Random r = new Random();
    Equipos local;
    Equipos visitante;
    
    private void partido(){
       
       try{
            local = (Equipos) cb_equipo1.getSelectedItem();
            visitante = (Equipos) cb_equipo2.getSelectedItem();
            int localr = r.nextInt(6)+0;
            int visitanter = r.nextInt(6)+0;
            local.setGf(local.getGf()+localr);
            local.setGc(local.getGc()+visitanter);

            visitante.setGf(visitante.getGf()+visitanter);
            visitante.setGc(visitante.getGc()+localr);

            if (localr == visitanter){
                local.setPts(local.getPts()+1);
                visitante.setPts(visitante.getPts()+1);
                JOptionPane.showMessageDialog(null, "Ha sido un empate");
            }else if(localr > visitanter){
                local.setPts(local.getPts()+3);
                JOptionPane.showMessageDialog(null, "Ha ganado el equipo local: " + local.getNombre());
            }else{
                visitante.setPts(visitante.getPts()+3);
                JOptionPane.showMessageDialog(null, "Ha ganado el equipo visitante: " + visitante.getNombre());
            }
            
            local.setDiff(local.getGf() - local.getGc());
            visitante.setDiff(visitante.getGf() - visitante.getGc());
            
            marcador_local.setText(""+localr);
            marcador_visitante.setText(""+visitanter);
       }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Ha ocurrido un error al simular el partido");
       }
       
    }
    private void ordenar (){
        
       Collections.sort(lista, new Comparator<Equipos>() {
            @Override
            public int compare(Equipos e1, Equipos e2) {
                if (e1.getPts() != e2.getPts()){
                    return new Integer(e2.getPts()).compareTo(new Integer(e1.getPts()));
                }else{
                    return new Integer(e2.getDiff()).compareTo(new Integer(e1.getDiff()));
                }    
            }
        });
    }
}
